### ISSUE TITLE
Homepage is not cleared 

### ISSUE THREAD

**Issue by mrmad** [VirtuBox/plesk-nginx-fascgi-cache-template#1]
Homepage is not cleared when a new post is published. There are a number of issues with nginx helper plugin (please check support threads).
Have you personally tested and do you mind sharing your settings? I have tested this on two different servers with the same result: once it is cached, the cache will never be cleared.

**Comment by VirtuBox** [comment]
Hello,
it's probably my fault because I forgot to add the requirements, nginx_cache_purge module is required to be able to purge the cache. I will add it asap
I use this template with nginx compiled with my script [nginx-ee](https://github.com/VirtuBox/nginx-ee)

**Comment by mrmad** [comment]
I am ALWAYS compile using your modified nginx version – that is not the problem. It is the plugin itself that does not do the job.
Can you confirm the homepage cache is cleared once a new post is published?

**Comment by VirtuBox** [comment]
Hello @mrmad,

please make sure purging conditions are properly set in nginx-helper settings : 
![nginx-helper](https://img.virtubox.net/images/2018/11/24/imaged115c8d59cdc29d8.png)
