### ISSUE TITLE
Error on Website & Dashboard Panel

### ISSUE THREAD

**Issue by cultd3ad** [VirtuBox/plesk-nginx-fascgi-cache-template#2]
Hello,

i become this Error Messages, reload and plesk repair web doesent not work for me. 

`New configuration files for the Apache web server were not created due to the errors in configuration templates: nginx: [emerg] "fastcgi_cache" directive is duplicate in /etc/nginx/plesk.conf.d/ip_default/**********.eu.conf:137 nginx: configuration file /etc/nginx/nginx.conf test failed . Detailed error descriptions were sent to you by email. Please resolve the issues and click here to generate broken configuration files once again or here to generate all configuration files. See the details in Configuration Troubleshooter`

any idea to fix this?

cult

**Comment by VirtuBox** [comment]
Hello @cultd3ad,

I do not use the ip_default feature in Plesk, so I will have to run few tests to reproduce this issue.

Regards,

**Comment by cultd3ad** [comment]
Hola,

ip_default is the default setting of Plesk, even if I change this setting I get the errors.

**Comment by VirtuBox** [comment]
> Hola,
> 
> ip_default is the default setting of Plesk, even if I change this setting I get the errors.

Hello,

is nginx cache enabled for your domains in Plesk ? 
If yes, just disable it in Plesk,  because this template already enable fastcgi cache when a domain is set in mode "Nginx Only".

**Comment by VirtuBox** [comment]
Hello @cultd3ad ,

I have updated the template to make it compatible with almost all Plesk configurations (related to Nginx cache et Nginx proxy mode). 
To update the template just run : 

```bash
git -C /usr/local/psa/admin/conf/templates/custom pull origin master
```

And relaunch plesk repair web to apply changes :

```bash
plesk repair web
```

**Comment by cultd3ad** [comment]
Hello VirtuBox,
thanks for your Work, i will test it :+1:
